/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Graph {
  positioning(): void
  describe(): GraphDescription
  clusterize(maxIters: number): Array<Cluster>
  get nodes(): Array<Node>
  get edges(): Array<Edge>
}

export interface Cluster {
  id: number
  members: Array<number>
}

export interface Edge {
  from: number
  to: number
}

export interface GraphDescription {
  nodes: Array<Node>
  edges: Array<Edge>
}

export interface Node {
  id: number
  label: string
  filePath: string
  position: [number, number]
}

export declare namespace typescript {
  export function getGraph(projectPath: string): Graph
}
