/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Edge {
  get from(): bigint
  get to(): bigint
}
export type NapiEdge = Edge

export declare class Graph {
  positioning(): void
  get nodes(): Array<NapiNode>
  get edges(): Array<NapiEdge>
}
export type NapiGraph = Graph

export declare class Node {
  get id(): bigint
  get label(): string
  get filePath(): string
  get position(): [number, number]
}
export type NapiNode = Node

export declare namespace typescript {
  export function getGraph(projectPath: string): Graph
}
