/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class ProjectLabeler {
  constructor(projectPath: string, projectFiles: Array<string>)
  labelFiles(selectedFiles: Array<string>): Record<string, number>
}
