import test from 'ava'

import { ProjectLabeler } from '../index'

test('sync function from native code', (t) => {
  const projectLabeler = new ProjectLabeler("/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume", [
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/examples/react-stream-example/src/vite-env.d.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/apps/cli/src/cli/create-server.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/apps/cli/src/cli/options/entry-option.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/apps/cli/src/cli/cli.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/apps/cli/src/cli/logger.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/apps/cli/src/cli/commands/build-command.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/apps/cli/src/cli/get-agrume-middleware.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/apps/cli/src/cli/find-entry-file.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/plugin/src/rspack.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/plugin/src/rolldown.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/plugin/src/utils/create-transform.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/plugin/src/webpack.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/plugin/src/farm.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/plugin/src/unplugin.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/plugin/src/esbuild.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/plugin/src/rollup.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/www/.vercel/output/static/_astro/client.dbacd924.js",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/www/.vercel/output/static/_astro/DocSearchbar.3ae1bc6a.js",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/www/.vercel/output/static/_astro/index.941f96af.js",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/www/astro.config.mjs",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/examples/react-stream-example/src/app.tsx",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/examples/react-stream-example/src/main.tsx",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/examples/react-stream-example/src/files.tsx",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/tunnel/src/tunnels/pinggy.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/tunnel/src/tunnels/localtunnel.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/tunnel/src/tunnels/abstract-tunnel.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/tunnel/src/tunnels/bore.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/tunnel/src/tunnels/ngrok.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/tunnel/src/tunnels/tunnels.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/tunnel/src/tunnel.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/agrume/tests-types/create-route-without-response.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/agrume/tests-types/simple-create-route.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/agrume/tests-types/create-route-with-iterator.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/agrume/tests-types/create-route-with-local-client.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/agrume/tests-types/create-route-with-typed-local-client.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/agrume/src/agrume.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/types/src/request-options.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/types/src/create-route.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/types/src/cli-options.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/types/src/types.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/types/src/route.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/types/src/global-options.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/types/src/plugin-options.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/commitlint.config.js",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/examples/agrume-cli-config-example/src/app.tsx",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/examples/agrume-cli-config-example/src/main.tsx",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/examples/agrume-cli-config-example/src/index.js",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/core/src/core.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/core/src/client/get-route-name.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/core/src/client/create-route.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/core/src/client/get-request-options.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/plugin/src/utils/vite/create-build-end.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/plugin/src/utils/vite/create-configure-server.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/internals/src/options/options.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/internals/src/state/state.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/internals/src/internals.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/babel-plugin-agrume/src/types/babel-argument-path.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/babel-plugin-agrume/src/utils/tree-shake.babel.js",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/babel-plugin-agrume/src/utils/create-argument-loader.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/babel-plugin-agrume/src/utils/get-program.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/babel-plugin-agrume/src/transforms/transform-call-expression.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/babel-plugin-agrume/src/agrume-plugin.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/builder/src/run-builder.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/builder/src/builder.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/builder/src/fastify/fastify-builder.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/apps/cli/src/index.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/www/src/env.d.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/builder/src/types/builder.d.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/examples/agrume-cli-config-example/agrume.config.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/examples/agrume-cli-config-example/vite.config.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/agrume/tests-e2e/create-route-with-iterator.test.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/agrume/tests-e2e/create-route-with-http-error.test.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/agrume/tests-e2e/create-route-with-global-client.test.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/agrume/tests-e2e/utils/format-stream-data.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/agrume/tests-e2e/utils/transform-agrume.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/agrume/tests-e2e/utils/load-agrume-project.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/agrume/tests-e2e/simplest-create-route.test.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/agrume/tests-e2e/create-route-empty-return.test.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/agrume/tests-e2e/create-route-with-generator-as-parameter.test.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/agrume/tests-e2e/create-route-with-custom-client.test.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/agrume/tests-e2e/agrume-plugin-has-prefix.test.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/plugin/src/vite.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/eslint-config/index.js",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/eslint.config.js",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/client/src/optimized/get-optimized-client.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/core/src/server/middleware.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/core/src/server/route-handler.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/core/src/server/connect-middleware.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/client/src/get-client.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/client/src/optimized/register.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/examples/react-example/vite.config.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/examples/react-example/server.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/examples/react-prisma-example/src/app.tsx",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/examples/react-prisma-example/src/main.tsx",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/examples/react-prisma-example/src/dog.tsx",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/examples/react-example/src/app.tsx",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/examples/react-example/src/dog-api-url.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/examples/react-example/src/main.tsx",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/examples/react-example/src/dog.tsx",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/examples/flow-example/src/app.jsx",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/examples/flow-example/src/index.jsx",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/babel-preset-agrume/src/untyped-libs.d.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/examples/agrume-cli-example/src/app.tsx",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/examples/agrume-cli-example/src/index.js",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/examples/vue-example/vite.config.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/eslint-config/src/types/eslint-plugin-filename-export.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/babel-plugin-agrume/build.config.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/agrume/build.config.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/eslint-config/src/agrume-eslint-config.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/examples/react-prisma-example/vite.config.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/internals/src/utils/read-config.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/internals/src/utils/define-config.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/internals/src/utils/utils.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/internals/src/utils/checksum.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/agrume/src/errors.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/examples/react-example/src/vite-env.d.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/www/src/components/searchbar/DocSearchbar.tsx",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/examples/vue-example/src/vite-env.d.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/agrume/tests-e2e/template/src/main.tsx",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/babel-preset-agrume/src/preset.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/examples/react-prisma-example/src/vite-env.d.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/examples/react-stream-example/vite.config.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/examples/react-stream-example/server.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/examples/react-diabolo-example/src/vite-env.d.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/examples/vue-example/src/main.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/examples/react-diabolo-example/src/route-service.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/examples/react-diabolo-example/src/app.tsx",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/examples/react-diabolo-example/src/main.tsx",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/www/src/components/searchbar/HighlightedDocument.tsx",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/www/src/utils/get-pages.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/examples/flow-example/vite.config.js",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/agrume/tests-e2e/template/src/vite-env.d.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/examples/vue-example/src/dog-api-url.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/examples/vue-example/src/get-dog-image.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/www/.vercel/output/static/_astro/page.d7d8fe59.js",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/examples/agrume-cli-config-example/src/vite-env.d.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/eslint-config/src/types/eslint-plugin-fp.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/eslint-config/src/types/eslint-plugin-filename-rules.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/www/src/utils/escape-html.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/examples/flow-example/flow-typed/vite_import_meta.js",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/apps/cli/src/cli/types/commander.d.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/examples/react-diabolo-example/vite.config.ts",
  ])

  const result = projectLabeler.labelFiles([
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/core/src/core.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/core/src/client/get-route-name.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/core/src/client/create-route.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/core/src/client/get-request-options.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/plugin/src/utils/vite/create-build-end.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/plugin/src/utils/vite/create-configure-server.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/internals/src/options/options.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/internals/src/state/state.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/internals/src/internals.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/babel-plugin-agrume/src/types/babel-argument-path.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/babel-plugin-agrume/src/utils/tree-shake.babel.js",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/babel-plugin-agrume/src/utils/create-argument-loader.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/babel-plugin-agrume/src/utils/get-program.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/babel-plugin-agrume/src/transforms/transform-call-expression.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/babel-plugin-agrume/src/agrume-plugin.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/builder/src/run-builder.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/builder/src/builder.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/packages/builder/src/fastify/fastify-builder.ts",
    "/Users/arthur-fontaine/Developer/code/github.com/arthur-fontaine/agrume/apps/cli/src/index.ts",
  ])

  console.dir(result, { depth: null });
  const sortedResults = Object.entries(result)
    .sort(([, a], [, b]) => b - a)
    .slice(0, 10);

  console.log("Top 10 Results:");
  sortedResults.forEach(([key, value]) => {
    console.log(`${key}: ${value}`);
  });

  t.assert(true);
})
