import path from 'node:path';
import { execSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import anyTest, { type TestFn } from 'ava'

import { ProjectLabeler } from '../index'

const test = anyTest as TestFn<{ projectDir: string }>;

test.before((t) => {
  const repoUrl = 'https://github.com/arthur-fontaine/agrume.git';
  const cloneDir = path.join(tmpdir(), `agrume-${Date.now()}`);

  execSync(`git clone ${repoUrl} ${cloneDir}`, { stdio: 'inherit' });

  t.context.projectDir = cloneDir;
});

test('sync function from native code', (t) => {
  const { projectDir } = t.context;

  const projectLabeler = new ProjectLabeler(projectDir, [
    `${projectDir}/examples/react-stream-example/src/vite-env.d.ts`,
    `${projectDir}/apps/cli/src/cli/create-server.ts`,
    `${projectDir}/apps/cli/src/cli/options/entry-option.ts`,
    `${projectDir}/apps/cli/src/cli/cli.ts`,
    `${projectDir}/apps/cli/src/cli/logger.ts`,
    `${projectDir}/apps/cli/src/cli/commands/build-command.ts`,
    `${projectDir}/apps/cli/src/cli/get-agrume-middleware.ts`,
    `${projectDir}/apps/cli/src/cli/find-entry-file.ts`,
    `${projectDir}/packages/plugin/src/rspack.ts`,
    `${projectDir}/packages/plugin/src/rolldown.ts`,
    `${projectDir}/packages/plugin/src/utils/create-transform.ts`,
    `${projectDir}/packages/plugin/src/webpack.ts`,
    `${projectDir}/packages/plugin/src/farm.ts`,
    `${projectDir}/packages/plugin/src/unplugin.ts`,
    `${projectDir}/packages/plugin/src/esbuild.ts`,
    `${projectDir}/packages/plugin/src/rollup.ts`,
    `${projectDir}/www/.vercel/output/static/_astro/client.dbacd924.js`,
    `${projectDir}/www/.vercel/output/static/_astro/DocSearchbar.3ae1bc6a.js`,
    `${projectDir}/www/.vercel/output/static/_astro/index.941f96af.js`,
    `${projectDir}/www/astro.config.mjs`,
    `${projectDir}/examples/react-stream-example/src/app.tsx`,
    `${projectDir}/examples/react-stream-example/src/main.tsx`,
    `${projectDir}/examples/react-stream-example/src/files.tsx`,
    `${projectDir}/packages/tunnel/src/tunnels/pinggy.ts`,
    `${projectDir}/packages/tunnel/src/tunnels/localtunnel.ts`,
    `${projectDir}/packages/tunnel/src/tunnels/abstract-tunnel.ts`,
    `${projectDir}/packages/tunnel/src/tunnels/bore.ts`,
    `${projectDir}/packages/tunnel/src/tunnels/ngrok.ts`,
    `${projectDir}/packages/tunnel/src/tunnels/tunnels.ts`,
    `${projectDir}/packages/tunnel/src/tunnel.ts`,
    `${projectDir}/packages/agrume/tests-types/create-route-without-response.ts`,
    `${projectDir}/packages/agrume/tests-types/simple-create-route.ts`,
    `${projectDir}/packages/agrume/tests-types/create-route-with-iterator.ts`,
    `${projectDir}/packages/agrume/tests-types/create-route-with-local-client.ts`,
    `${projectDir}/packages/agrume/tests-types/create-route-with-typed-local-client.ts`,
    `${projectDir}/packages/agrume/src/agrume.ts`,
    `${projectDir}/packages/types/src/request-options.ts`,
    `${projectDir}/packages/types/src/create-route.ts`,
    `${projectDir}/packages/types/src/cli-options.ts`,
    `${projectDir}/packages/types/src/types.ts`,
    `${projectDir}/packages/types/src/route.ts`,
    `${projectDir}/packages/types/src/global-options.ts`,
    `${projectDir}/packages/types/src/plugin-options.ts`,
    `${projectDir}/commitlint.config.js`,
    `${projectDir}/examples/agrume-cli-config-example/src/app.tsx`,
    `${projectDir}/examples/agrume-cli-config-example/src/main.tsx`,
    `${projectDir}/examples/agrume-cli-config-example/src/index.js`,
    `${projectDir}/packages/core/src/core.ts`,
    `${projectDir}/packages/core/src/client/get-route-name.ts`,
    `${projectDir}/packages/core/src/client/create-route.ts`,
    `${projectDir}/packages/core/src/client/get-request-options.ts`,
    `${projectDir}/packages/plugin/src/utils/vite/create-build-end.ts`,
    `${projectDir}/packages/plugin/src/utils/vite/create-configure-server.ts`,
    `${projectDir}/packages/internals/src/options/options.ts`,
    `${projectDir}/packages/internals/src/state/state.ts`,
    `${projectDir}/packages/internals/src/internals.ts`,
    `${projectDir}/packages/babel-plugin-agrume/src/types/babel-argument-path.ts`,
    `${projectDir}/packages/babel-plugin-agrume/src/utils/tree-shake.babel.js`,
    `${projectDir}/packages/babel-plugin-agrume/src/utils/create-argument-loader.ts`,
    `${projectDir}/packages/babel-plugin-agrume/src/utils/get-program.ts`,
    `${projectDir}/packages/babel-plugin-agrume/src/transforms/transform-call-expression.ts`,
    `${projectDir}/packages/babel-plugin-agrume/src/agrume-plugin.ts`,
    `${projectDir}/packages/builder/src/run-builder.ts`,
    `${projectDir}/packages/builder/src/builder.ts`,
    `${projectDir}/packages/builder/src/fastify/fastify-builder.ts`,
    `${projectDir}/apps/cli/src/index.ts`,
    `${projectDir}/www/src/env.d.ts`,
    `${projectDir}/packages/builder/src/types/builder.d.ts`,
    `${projectDir}/examples/agrume-cli-config-example/agrume.config.ts`,
    `${projectDir}/examples/agrume-cli-config-example/vite.config.ts`,
    `${projectDir}/packages/agrume/tests-e2e/create-route-with-iterator.test.ts`,
    `${projectDir}/packages/agrume/tests-e2e/create-route-with-http-error.test.ts`,
    `${projectDir}/packages/agrume/tests-e2e/create-route-with-global-client.test.ts`,
    `${projectDir}/packages/agrume/tests-e2e/utils/format-stream-data.ts`,
    `${projectDir}/packages/agrume/tests-e2e/utils/transform-agrume.ts`,
    `${projectDir}/packages/agrume/tests-e2e/utils/load-agrume-project.ts`,
    `${projectDir}/packages/agrume/tests-e2e/simplest-create-route.test.ts`,
    `${projectDir}/packages/agrume/tests-e2e/create-route-empty-return.test.ts`,
    `${projectDir}/packages/agrume/tests-e2e/create-route-with-generator-as-parameter.test.ts`,
    `${projectDir}/packages/agrume/tests-e2e/create-route-with-custom-client.test.ts`,
    `${projectDir}/packages/agrume/tests-e2e/agrume-plugin-has-prefix.test.ts`,
    `${projectDir}/packages/plugin/src/vite.ts`,
    `${projectDir}/packages/eslint-config/index.js`,
    `${projectDir}/eslint.config.js`,
    `${projectDir}/packages/client/src/optimized/get-optimized-client.ts`,
    `${projectDir}/packages/core/src/server/middleware.ts`,
    `${projectDir}/packages/core/src/server/route-handler.ts`,
    `${projectDir}/packages/core/src/server/connect-middleware.ts`,
    `${projectDir}/packages/client/src/get-client.ts`,
    `${projectDir}/packages/client/src/optimized/register.ts`,
    `${projectDir}/examples/react-example/vite.config.ts`,
    `${projectDir}/examples/react-example/server.ts`,
    `${projectDir}/examples/react-prisma-example/src/app.tsx`,
    `${projectDir}/examples/react-prisma-example/src/main.tsx`,
    `${projectDir}/examples/react-prisma-example/src/dog.tsx`,
    `${projectDir}/examples/react-example/src/app.tsx`,
    `${projectDir}/examples/react-example/src/dog-api-url.ts`,
    `${projectDir}/examples/react-example/src/main.tsx`,
    `${projectDir}/examples/react-example/src/dog.tsx`,
    `${projectDir}/examples/flow-example/src/app.jsx`,
    `${projectDir}/examples/flow-example/src/index.jsx`,
    `${projectDir}/packages/babel-preset-agrume/src/untyped-libs.d.ts`,
    `${projectDir}/examples/agrume-cli-example/src/app.tsx`,
    `${projectDir}/examples/agrume-cli-example/src/index.js`,
    `${projectDir}/examples/vue-example/vite.config.ts`,
    `${projectDir}/packages/eslint-config/src/types/eslint-plugin-filename-export.ts`,
    `${projectDir}/packages/babel-plugin-agrume/build.config.ts`,
    `${projectDir}/packages/agrume/build.config.ts`,
    `${projectDir}/packages/eslint-config/src/agrume-eslint-config.ts`,
    `${projectDir}/examples/react-prisma-example/vite.config.ts`,
    `${projectDir}/packages/internals/src/utils/read-config.ts`,
    `${projectDir}/packages/internals/src/utils/define-config.ts`,
    `${projectDir}/packages/internals/src/utils/utils.ts`,
    `${projectDir}/packages/internals/src/utils/checksum.ts`,
    `${projectDir}/packages/agrume/src/errors.ts`,
    `${projectDir}/examples/react-example/src/vite-env.d.ts`,
    `${projectDir}/www/src/components/searchbar/DocSearchbar.tsx`,
    `${projectDir}/examples/vue-example/src/vite-env.d.ts`,
    `${projectDir}/packages/agrume/tests-e2e/template/src/main.tsx`,
    `${projectDir}/packages/babel-preset-agrume/src/preset.ts`,
    `${projectDir}/examples/react-prisma-example/src/vite-env.d.ts`,
    `${projectDir}/examples/react-stream-example/vite.config.ts`,
    `${projectDir}/examples/react-stream-example/server.ts`,
    `${projectDir}/examples/react-diabolo-example/src/vite-env.d.ts`,
    `${projectDir}/examples/vue-example/src/main.ts`,
    `${projectDir}/examples/react-diabolo-example/src/route-service.ts`,
    `${projectDir}/examples/react-diabolo-example/src/app.tsx`,
    `${projectDir}/examples/react-diabolo-example/src/main.tsx`,
    `${projectDir}/www/src/components/searchbar/HighlightedDocument.tsx`,
    `${projectDir}/www/src/utils/get-pages.ts`,
    `${projectDir}/examples/flow-example/vite.config.js`,
    `${projectDir}/packages/agrume/tests-e2e/template/src/vite-env.d.ts`,
    `${projectDir}/examples/vue-example/src/dog-api-url.ts`,
    `${projectDir}/examples/vue-example/src/get-dog-image.ts`,
    `${projectDir}/www/.vercel/output/static/_astro/page.d7d8fe59.js`,
    `${projectDir}/examples/agrume-cli-config-example/src/vite-env.d.ts`,
    `${projectDir}/packages/eslint-config/src/types/eslint-plugin-fp.ts`,
    `${projectDir}/packages/eslint-config/src/types/eslint-plugin-filename-rules.ts`,
    `${projectDir}/www/src/utils/escape-html.ts`,
    `${projectDir}/examples/flow-example/flow-typed/vite_import_meta.js`,
    `${projectDir}/apps/cli/src/cli/types/commander.d.ts`,
    `${projectDir}/examples/react-diabolo-example/vite.config.ts`,
  ])

  const result = projectLabeler.labelFiles([
    `${projectDir}/packages/core/src/core.ts`,
    `${projectDir}/packages/core/src/client/get-route-name.ts`,
    `${projectDir}/packages/core/src/client/create-route.ts`,
    `${projectDir}/packages/core/src/client/get-request-options.ts`,
    `${projectDir}/packages/plugin/src/utils/vite/create-build-end.ts`,
    `${projectDir}/packages/plugin/src/utils/vite/create-configure-server.ts`,
    `${projectDir}/packages/internals/src/options/options.ts`,
    `${projectDir}/packages/internals/src/state/state.ts`,
    `${projectDir}/packages/internals/src/internals.ts`,
    `${projectDir}/packages/babel-plugin-agrume/src/types/babel-argument-path.ts`,
    `${projectDir}/packages/babel-plugin-agrume/src/utils/tree-shake.babel.js`,
    `${projectDir}/packages/babel-plugin-agrume/src/utils/create-argument-loader.ts`,
    `${projectDir}/packages/babel-plugin-agrume/src/utils/get-program.ts`,
    `${projectDir}/packages/babel-plugin-agrume/src/transforms/transform-call-expression.ts`,
    `${projectDir}/packages/babel-plugin-agrume/src/agrume-plugin.ts`,
    `${projectDir}/packages/builder/src/run-builder.ts`,
    `${projectDir}/packages/builder/src/builder.ts`,
    `${projectDir}/packages/builder/src/fastify/fastify-builder.ts`,
    `${projectDir}/apps/cli/src/index.ts`,
  ])

  console.dir(result, { depth: null });
  const sortedResults = Object.entries(result)
    .sort(([, a], [, b]) => b - a)
    .slice(0, 10);

  console.log("Top 10 Results:");
  sortedResults.forEach(([key, value]) => {
    console.log(`${key}: ${value}`);
  });

  t.assert(true);
})
